package com.juancnuno.adventofcode2023.day11.test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

import com.juancnuno.adventofcode2023.day11.Universe;

public final class UniverseTest {

    @Test
    public void expand1() {
        // Arrange
        var universe = Universe.valueOf("""
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
            """);

        // Act
        var actual = universe.expand();

        // Assert
        var expected = Universe.valueOf("""
            ....#........
            .........#...
            #............
            .............
            .............
            ........#....
            .#...........
            ............#
            .............
            .............
            .........#...
            #....#.......
            """);

        assertEquals(expected, actual);
    }

    @Test
    public void expand2() {
        // Arrange
        var universe = Universe.valueOf("""
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
            """);

        // Act
        var actual = universe.expand(3);

        // Assert
        var expected = Universe.valueOf("""
            .....#..........
            ...........#....
            #...............
            ................
            ................
            ................
            ..........#.....
            .#..............
            ...............#
            ................
            ................
            ................
            ...........#....
            #.....#.........
            """);

        assertEquals(expected, actual);
    }

    @Test
    public void getDistanceSum1() {
        // Arrange
        var universe = Universe.valueOf("""
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
            """);

        // Act
        var sum = universe.getDistanceSum();

        // Assert
        assertEquals(374, sum);
    }

    @Test
    public void getDistanceSum2() {
        // Arrange
        var universe = Universe.valueOf("""
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
            """);

        // Act
        var sum = universe.getDistanceSum(10);

        // Assert
        assertEquals(1_030, sum);
    }

    @Test
    public void testToString() {
        // Arrange
        var rows = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
            """;

        var universe = Universe.valueOf(rows);

        // Act
        var string = universe.toString();

        // Assert
        assertEquals(rows, string);
    }
}
